[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
arch = "arm64-v8a"
patcher-args = "-e 'GmsCore support' -OgmsCoreVendorGroupId=tv.danmaku.bili -e 'Custom branding' -OcustomName=tv.danmaku.bili"

